add_newline = false

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$sudo\
$cmd_duration\
$jobs\
$character"""

[line_break]
disabled = true

[sudo]
disabled = false

[cmd_duration]
show_notifications = true
